"""Generate Typst source and compile PDF reports from career council deliberations."""

import subprocess
import tempfile
import os
from pathlib import Path
from typing import Dict, Any
from datetime import datetime


def escape_typst(text: str) -> str:
    """Escape special Typst characters in user/LLM text."""
    # Typst special chars: #, @, $, <, >, *, _, `
    replacements = [
        ("\\", "\\\\"),
        ("#", "\\#"),
        ("@", "\\@"),
        ("$", "\\$"),
        ("<", "\\<"),
        (">", "\\>"),
        ("*", "\\*"),
        ("_", "\\_"),
        ("`", "\\`"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def generate_typst_source(results: Dict[str, Any], background: str) -> str:
    """Generate Typst source document from career council results."""
    mode_label = results.get("mode_label", results["mode"])
    stage1 = results["stage1"]
    stage2 = results["stage2"]
    stage3 = results["stage3"]
    metadata = results.get("metadata", {})
    aggregate = metadata.get("aggregate_rankings", [])
    now = datetime.now().strftime("%B %d, %Y")

    # Build stage 1 section
    stage1_blocks = []
    for r in stage1:
        stage1_blocks.append(f"""
#block(
  fill: luma(245),
  inset: 12pt,
  radius: 4pt,
  width: 100%,
)[
  #text(weight: "bold", size: 11pt)[{escape_typst(r['name'])}] #h(6pt) #text(style: "italic", fill: luma(100))[{escape_typst(r['tagline'])}]

  #line(length: 100%, stroke: 0.5pt + luma(200))

  {escape_typst(r['response'])}
]""")

    # Build stage 2 section
    stage2_blocks = []
    for r in stage2:
        stage2_blocks.append(f"""
#block(
  fill: rgb("#fff8f0"),
  inset: 12pt,
  radius: 4pt,
  width: 100%,
)[
  #text(weight: "bold", size: 11pt)[{escape_typst(r['name'])}]

  #line(length: 100%, stroke: 0.5pt + luma(200))

  {escape_typst(r['ranking'])}
]""")

    # Build rankings table
    rankings_rows = ""
    for rank in aggregate:
        rankings_rows += f'  [{rank.get("name", "?")}], [{rank.get("average_rank", "?")}], [{rank.get("rankings_count", "?")}],\n'

    typst_source = f"""// Council of Maniacs — Career Report
// Auto-generated {now}

#set document(
  title: "Council of Maniacs: {escape_typst(mode_label)}",
  date: auto,
)

#set page(
  paper: "a4",
  margin: (x: 2cm, y: 2.5cm),
  header: align(right)[
    #text(size: 8pt, fill: luma(150))[Council of Maniacs — Career Division]
  ],
  footer: context [
    #align(center)[
      #text(size: 8pt, fill: luma(150))[Page #counter(page).display("1 of 1", both: true)]
    ]
  ],
)

#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.65em)
#set heading(numbering: "1.")

// Title page
#align(center)[
  #v(3cm)
  #text(size: 28pt, weight: "bold")[Council of Maniacs]

  #v(0.5cm)
  #text(size: 16pt, fill: luma(80))[Career Division]

  #v(1cm)
  #line(length: 60%, stroke: 2pt + rgb("#e74c3c"))

  #v(0.5cm)
  #text(size: 18pt, weight: "bold")[{escape_typst(mode_label)}]

  #v(2cm)
  #text(size: 11pt, fill: luma(100))[{now}]
]

#pagebreak()

// Table of contents
#outline(indent: 1.5em, depth: 2)
#pagebreak()

= Background

The following professional background was submitted for deliberation:

#block(
  fill: rgb("#f0f4ff"),
  inset: 14pt,
  radius: 4pt,
  width: 100%,
)[
  {escape_typst(background)}
]

#pagebreak()

= Stage 1: The Maniacs Respond

Each council member reviewed the background and proposed {escape_typst(mode_label.lower())} in their own unhinged style.

{''.join(stage1_blocks)}

#pagebreak()

= Stage 2: Peer Review

Each maniac evaluated the others' proposals — in character, naturally.

{''.join(stage2_blocks)}

#{"" if not aggregate else f'''
== Aggregate Rankings

#table(
  columns: (1fr, auto, auto),
  inset: 8pt,
  align: (left, center, center),
  fill: (_, row) => if row == 0 {{ rgb("#e74c3c").lighten(80%) }} else {{ none }},
  [*Council Member*], [*Avg Rank*], [*Votes*],
{rankings_rows})
'''}

#pagebreak()

= Stage 3: The Moderator's Verdict

The Moderator reviewed all proposals and peer evaluations to extract genuinely actionable ideas.

#block(
  fill: rgb("#f0fff0"),
  inset: 14pt,
  radius: 4pt,
  width: 100%,
)[
  {escape_typst(stage3['response'])}
]

#v(2cm)
#align(center)[
  #text(size: 9pt, fill: luma(150))[
    Generated by the Council of Maniacs — Career Division \\
    All ideas proposed by AI personas. Sanity not guaranteed.
  ]
]
"""
    return typst_source


def compile_pdf(results: Dict[str, Any], background: str, output_path: str) -> str:
    """Generate Typst source and compile to PDF. Returns the output path."""
    typst_src = generate_typst_source(results, background)

    output_path = os.path.abspath(output_path)
    output_dir = os.path.dirname(output_path)
    os.makedirs(output_dir, exist_ok=True)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".typ", delete=False) as f:
        f.write(typst_src)
        typ_path = f.name

    try:
        result = subprocess.run(
            ["typst", "compile", typ_path, output_path],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Typst compilation failed:\n{result.stderr}")
        return output_path
    finally:
        os.unlink(typ_path)


def save_typst_source(results: Dict[str, Any], background: str, output_path: str) -> str:
    """Save the Typst source file (without compiling). Returns the output path."""
    typst_src = generate_typst_source(results, background)
    output_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(typst_src)
    return output_path
